In [16]:
from random import random
import numpy as np
from google.colab.patches import cv2
import matplotlib.pyplot as plt

def convolution_2D_layer(A, B):
    m, n = A.shape
    p, q = B.shape
    C = np.zeros((m+p-1, n+q-1))
    # Crs = Aij * Bkl i+k=r+1 & j+l=s+1
    for r in range(m+p-1):
        for s in range(n+q-1):
            for i in range(m):
                for j in range(n):
                    k = r + 1 - i
                    l = s + 1 - j
                    if k>=0 and k<p and l>=0 and l<q:
                        C[r][s] += A[i][j] * B[k][l]

    return C

def main():
    # PART A
    A = np.random.randint(2, size=(8, 6))
    B = np.array([[-1, 1], [1, -1]])
    print("A = \n", A)
    print("B = \n", B)
    C = convolution_2D_layer(A, B)
    print("C = \n", C)

    # PART B
    A = cv2.imread("zero.jpeg", 0)
    D = np.array([[1, -1]])
    C = convolution_2D_layer(A, D)
    # cv2.imshow("A", A)
    # cv2.imshow("C", C)
    cv2.imwrite("zero_edge.jpg", C)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

    A = cv2.imread("nine.jpeg", 0)
    D = np.array([[1, -1]])
    C = convolution_2D_layer(A, D)
    #cv2.imshow("A", A)
    #cv2.imshow("C"  , C)
    cv2.imwrite("nine_edge.jpg", C)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

    
    A = cv2.imread("one.jpeg", 0)
    D = np.array([[1, -1]])
    C = convolution_2D_layer(A, D)
    #cv2.imshow("A", A)
    #cv2.imshow("C"  , C)
    cv2.imwrite("one_edge.jpg", C)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

if __name__ == "__main__":
    main()

A = 
 [[0 1 1 0 1 0]
 [1 0 0 1 0 0]
 [1 1 1 0 1 0]
 [0 0 0 0 1 0]
 [0 1 1 0 1 0]
 [1 0 1 0 1 0]
 [0 0 0 0 0 1]
 [1 1 1 1 0 0]]
B = 
 [[-1  1]
 [ 1 -1]]
C = 
 [[ 2.  0. -2.  2. -1.  0.  0.]
 [-1.  0.  2. -2.  1.  0.  0.]
 [ 0.  0. -1.  0.  0.  0.  0.]
 [-1.  0.  1.  0.  0.  0.  0.]
 [ 2. -1.  0.  0.  0.  0.  0.]
 [-1.  1. -1.  1. -2.  1.  0.]
 [ 0.  0.  0.  1.  1. -1.  0.]
 [ 0.  0.  0. -1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]]
